/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentMethodInput = IDL.Record({
  'nickname' : IDL.Text,
  'last4' : IDL.Text,
  'brand' : IDL.Text,
  'expiry' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const DatingProfile = IDL.Record({
  'id' : IDL.Principal,
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'interestedIn' : Gender,
  'gender' : Gender,
  'locationText' : IDL.Text,
  'photos' : IDL.Vec(IDL.Text),
});
export const Message = IDL.Record({
  'to' : IDL.Principal,
  'content' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const PaymentMethod = IDL.Record({
  'id' : IDL.Text,
  'nickname' : IDL.Text,
  'createdAt' : IDL.Int,
  'last4' : IDL.Text,
  'brand' : IDL.Text,
  'expiry' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPaymentMethod' : IDL.Func([PaymentMethodInput], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DatingProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDefaultPaymentMethod' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getDiscoveryFeed' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DatingProfile)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getSavedPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DatingProfile)],
      ['query'],
    ),
  'isBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeProfile' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'removePaymentMethod' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([DatingProfile], [DatingProfile], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setDefaultPaymentMethod' : IDL.Func([IDL.Text], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updatePaymentMethod' : IDL.Func([IDL.Text, PaymentMethodInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentMethodInput = IDL.Record({
    'nickname' : IDL.Text,
    'last4' : IDL.Text,
    'brand' : IDL.Text,
    'expiry' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const DatingProfile = IDL.Record({
    'id' : IDL.Principal,
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'interestedIn' : Gender,
    'gender' : Gender,
    'locationText' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
  });
  const Message = IDL.Record({
    'to' : IDL.Principal,
    'content' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const PaymentMethod = IDL.Record({
    'id' : IDL.Text,
    'nickname' : IDL.Text,
    'createdAt' : IDL.Int,
    'last4' : IDL.Text,
    'brand' : IDL.Text,
    'expiry' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPaymentMethod' : IDL.Func([PaymentMethodInput], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DatingProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDefaultPaymentMethod' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getDiscoveryFeed' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DatingProfile)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getSavedPaymentMethods' : IDL.Func(
        [],
        [IDL.Vec(PaymentMethod)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DatingProfile)],
        ['query'],
      ),
    'isBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeProfile' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'removePaymentMethod' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([DatingProfile], [DatingProfile], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setDefaultPaymentMethod' : IDL.Func([IDL.Text], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updatePaymentMethod' : IDL.Func([IDL.Text, PaymentMethodInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };