/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DatingProfile {
  'id' : Principal,
  'age' : bigint,
  'bio' : string,
  'displayName' : string,
  'interestedIn' : Gender,
  'gender' : Gender,
  'locationText' : string,
  'photos' : Array<string>,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Message {
  'to' : Principal,
  'content' : string,
  'from' : Principal,
  'timestamp' : bigint,
}
export interface PaymentMethod {
  'id' : string,
  'nickname' : string,
  'createdAt' : bigint,
  'last4' : string,
  'brand' : string,
  'expiry' : string,
}
export interface PaymentMethodInput {
  'nickname' : string,
  'last4' : string,
  'brand' : string,
  'expiry' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPaymentMethod' : ActorMethod<[PaymentMethodInput], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [DatingProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDefaultPaymentMethod' : ActorMethod<[], [] | [string]>,
  'getDiscoveryFeed' : ActorMethod<[bigint, bigint], Array<DatingProfile>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getSavedPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [DatingProfile]>,
  'isBlocked' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeProfile' : ActorMethod<[Principal], boolean>,
  'removePaymentMethod' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[DatingProfile], DatingProfile>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'setDefaultPaymentMethod' : ActorMethod<[string], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updatePaymentMethod' : ActorMethod<[string, PaymentMethodInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];